# Generated by Django 5.0.6 on 2024-05-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_sms_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_verified',
            field=models.BooleanField(default=False),
        ),
    ]
